# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Zhiyun Song (宋志云)
description: >- # this means to ignore newlines until "baseurl:"
  Zhiyun Song's Homepage
baseurl: "" # the subpath of the site
url: "https://zhiyuns.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpeg

header:
  pages:
    - name: Home
      slug: /
    - name: Research
    - name: Publications

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: zhiyunsung@gmail.com
      link: mailto:zhiyunsung@gmail.com
  follow:
    - name: GitHub
      link: http://github.com/zhiyuns

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
